version: "3.8"
services:
  proyecto:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "jupyter notebook --allow-root"
    ports:
      - "80:8080"
    volumes:
      - ./data:/root/data
      - ./notebooks:/root/notebooks
